### PR TITLE
rename composite-chapter to composite-appendix

### PR DESCRIPTION
**Pull request by philschatz**
oops, forgot to rename that attribute to clarify that the thing being generated is an appendix, not a chapter.

refs #174

### CODE REVIEW

**Comment by reedstrm** [comment]
https://github.com/Connexions/cnx-epub/blob/master/cnxepub/adapters.py#L488

**Comment by reedstrm** [comment]
The place for the subtype-specific info is probably the data-uuid-key, anyway.

**Comment by philschatz** [comment]
oh, in that case I should change the name of the config variable that adds these things in. My understanding was that some of the books wanted an Appendix for each Unit (or multiple pages inside an appendix) instead of having 1-page Appendixes at the end of a book.

See https://github.com/Connexions/cnx-rulesets/pull/189/files#diff-153bd716f5fa0585a5cfebf41a4e187bR17 for the variable name and the code that creates `composite-chapter` uses other variables with the word "Appendix" in them.

**Comment by philschatz** [comment]
Closing this because a "chapter" is a structural type (it can only have Page children) while a "Chapter" is a presentational element (like an Appendix or Preface).

So, I think it makes sense to keep the CSS as `composite-chapter` while keeping the config field `$Config_hasCompositeAppendixes`

/cc @helenemccarron

**Pull request closed without merging**
